### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by chendrix** [stephencelis/app#12]
Hi there,

Can you please cut a new version of the gem and push it to rubygems? I am having issues pulling gems from github and yours happens to be my only github dependency.

Thanks,
Chris

**Comment by stephencelis** [comment]
Your wish is my command: :sparkles: https://rubygems.org/gems/app/versions/1.2.0 :sparkles:

**Comment by chendrix** [comment]
Thanks! +1

On Thursday, February 26, 2015, Stephen Celis notifications@github.com
wrote:

> Closed #12 https://github.com/stephencelis/app/issues/12.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stephencelis/app/issues/12#event-242933842.

##
